Operator:
  Namespace: opennms
  serviceName: opennms-operator
  image: opennms/operator:latest
  imagePullPolicy: IfNotPresent
  imageUpdateFreq: 60
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi
  devMode: false
customErrors:
  image: quay.io/kubernetes-ingress-controller/custom-error-pages-amd64:0.4
  debug: true
TLS:
  Enabled: true
NodeRestrictions: # will be applied to every pod in the instance
  Enabled: false
  Key: kubernetes.azure.com/scalesetpriority
  Value: spot
