Namespace: opennms-instance
Host: onmshs
TestDeploy: false
OpenNMS:
  Core:
    Path: /core
    ServiceName: opennms-core
    Image: opennms/horizon-stream-core
    Replicas: 1
    HttpPort: 8181
    SshPort: 8101
    GrpcPort: 8990
    Resources:
      Limits:
        Cpu: 2
        Memory: 4Gi
      Requests:
        Cpu: 2
        Memory: 2Gi
  API:
    Path: /api
    ServiceName: opennms-rest-server
    Image: opennms/horizon-stream-rest-server
    Replicas: 1
    Port: 9090
    Resources:
      Limits:
        Cpu: 2
        Memory: 2Gi
      Requests:
        Cpu: 1
        Memory: 1Gi
  UI:
    Path: /
    ServiceName: opennms-ui
    Image: opennms/horizon-stream-ui
    Replicas: 1
    Port: 80
    Resources:
      Limits:
        Cpu: 1
        Memory: 500Mi
      Requests:
        Cpu: 100m
        Memory: 250Mi
  Minion:
    ServiceName: opennms-minion
    Image: opennms/minion:29.0.10
    Replicas: 1
    SshPort: 8201
    SnmpPort: 1162
    SyslogPort: 1514
    Resources:
      Limits:
        Cpu: 1
        Memory: 2050M
      Requests:
        Cpu: 1
        Memory: 512Mi
  Notification: 
    ServiceName: opennms-notifications
    Image: opennms/horizon-stream-notification
    Replicas: 1
    Port: 8080
    Resources:
      Limits:
        Cpu: 1
        Memory: 500Mi
      Requests:
        Cpu: 100m
        Memory: 250Mi
Postgres:
  ServiceName: postgres
  Image: postgres
  Replicas: 1
  AdminPassword: notset
  OpenNMSPassword: notset
  KeycloakPassword: notset
  NotificationPassword: notset
  GrafanaPassword: notset
  VolumeSize: 10Gi
Keycloak:
  Path: /auth
  Image: opennms/horizon-stream-keycloak:latest
  Port: 8080
  HttpsPort: 8443
  Replicas: 1
  ServiceName: onms-keycloak
  Resources:
    Limits:
      Cpu: 1
      Memory: 1000Mi
    Requests:
      Cpu: 100m
      Memory: 500Mi
  AdminUsername: admin
  AdminPassword: notset
  UserUsername: user001
  UserPassword: notset
  RealmName: opennms
  UUID:
    RealmId: 00000000-0000-0000-0000-000000000000
    ClientId: 00000000-0000-0000-0000-000000000000
    BaseUserId: 00000000-0000-0000-0000-000000000000
    AdminUserId: 00000000-0000-0000-0000-000000000000
Grafana:
  Path: /grafana
  Port: 3000
  Replicas: 1
  ServiceName: grafana
  Image: opennms/horizon-stream-grafana
  InitContainerImage: busybox
  Resources:
    Limits:
      Cpu: 500m
      Memory: 1Gi
    Requests:
      Cpu: 100m
      Memory: 100Mi
Prometheus:
  Enabled: true
  Server:
    ServiceName: prometheus
    Port: 9090
    Image: prom/prometheus
    Replicas: 1
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi
  PushGateway:
    ServiceName: prometheus-pushgateway
    Port: 9091
    Image: prom/pushgateway
    Replicas: 1
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi
Kafka:
  ServiceName: onms-kafka
  Image: quay.io/strimzi/kafka:latest-kafka-2.8.1-amd64
  Replicas: 1 
  Port: 9092
  Resources:
    Limits:
      Cpu: 500m
      Memory: 512Mi
    Requests:
      Cpu: 100m
      Memory: 256Mi
  VolumeSize: 10Gi
MailServer:
  ServiceName: mail-server
  Image: mailhog/mailhog:latest
  Replicas: 1 
  Port: 8025
  SmtpPort: 1025
  Resources:
    Limits:
      Cpu: 100m
      Memory: 200Mi
    Requests:
      Cpu: 100m
      Memory: 100Mi
Ingress:
  HttpPort: 80
  HttpsPort: 443
  ControllerImage: registry.k8s.io/ingress-nginx/controller:v1.3.0@sha256:d1707ca76d3b044ab8a28277a2466a02100ee9f58a86af1535a3edf9323ea1b5
  SecretJobImage: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
  WebhookPatchJobImage: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660


