# nonk8s
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: parent-pom
build:
  local:
    push: false
  artifacts:
  - image: parent-pom
    custom:
      # parent-pom builds only a jar, not an image.
      # Skaffold requires that artifacts produce images. This is a workaround that builds a dummy image.
      buildCommand: |
        mvn clean install -DskipTests=$SKIP_TEST &&
        echo 'FROM scratch' | docker build -t $IMAGE -
      dependencies:
        paths: ["pom.xml"]
