apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opennms-ingress
  namespace: {{ .Values.Namespace }}
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ .Values.OpenNMS.UI.ServiceName }}
      port:
        number: {{ .Values.OpenNMS.UI.Port }}
  rules:
    - host: {{ .Values.Host }}
      http:
        paths:
          - path: {{ .Values.OpenNMS.UI.Path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.OpenNMS.UI.ServiceName }}
                port:
                  number: {{ .Values.OpenNMS.UI.Port }}
          - path: {{ .Values.Keycloak.Path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.Keycloak.ServiceName }}
                port:
                  number: {{ .Values.Keycloak.Port }}
          - path: {{ .Values.OpenNMS.API.Path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.OpenNMS.API.ServiceName }}
                port:
                  number: {{ .Values.OpenNMS.API.Port }}
          - path: {{ .Values.Grafana.Path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.Grafana.ServiceName }}
                port:
                  number: {{ .Values.Grafana.Port }}
  {{ if .Values.TLS.Enabled }}
  tls:
    - hosts:
        -  {{.Values.Host }}
      secretName: {{ .Values.TLS.Cert.Name }}
  {{ end }}
