apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: {{ .Values.Kafka.ServiceName }}
  namespace: {{ .Values.Namespace }}
spec:
  ports:
    - port: {{ .Values.Kafka.Port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.Kafka.Port }}
  selector:
    app: {{ .Values.Kafka.ServiceName }}
  type: ClusterIP