# nonk8s
## LOCAL PORT ASSIGNMENTS (note internal ports use the native port number)
##	xx = service/container
##	xx080 = HTTP
##	xx089 = GRPC
##	xx022 = SSH
##	xx025 = SMTP (mail)
##	xx050 = JAVA DEBUG
##	xx054 = POSTGRES
##	xx090 = KAFKA
##
## 11 = horizon-stream-core
## 12 = horizon-stream-minion
## 13 = horizon-stream-api
## 14 = api-gateway
## 15 = horizon-stream-notification
## 16 = horizon-stream-minion-gateway
## 17 = horizon-stream-ui
## 18 = grafana
## 19 = prometheus
## 21 = prometheus-pushgateway
## 22 = mail-server
## 23 = zookeeper
## 24 = kafka
## 25 = postgres
## 26 = keycloak
## 27 = minion (classic)
## 28 = horizon-stream-inventory
##

apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: horizon-stream
requires:
  - configs: ["shared-lib"]
    path: shared-lib/skaffold.yaml
  - configs: ["horizon-stream-ui"]
    path: ui/skaffold.yaml
  - configs: ["minion-gateway"]
    path: minion-gateway/skaffold.yaml
  - configs: ["operator"]
    path: operator/skaffold.yaml
build:
  local:
    useBuildkit: true
  artifacts:
  - image: opennms/horizon-stream-core
    context: platform
    custom:
      buildCommand: "mvn install -Pbuild-docker-images-enabled -DskipTests=$SKIP_TEST -Ddocker.image=$IMAGE -Ddocker.skipPush={{ .PUSH_IMAGE | not }}"
      dependencies:
        paths: ["."]
        ignore: [
          "**/target/**",
          "**/dependency-reduced-pom.xml" # generated by maven-shade-plugin, these cause file watching to break when running `skaffold debug`
        ]
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-minion
    context: minion
    custom:
      buildCommand: "mvn install -Dtest={{ .SKIP_TEST | not }} -DfailIfNoTests=false -DskipITs=true -DskipTests=$SKIP_TEST -Ddocker.image=$IMAGE -Ddocker.skipPush={{ .PUSH_IMAGE | not }}"
      dependencies:
        paths: ["."]
        ignore: [
          "**/target/**",
          "**/dependency-reduced-pom.xml" # generated by maven-shade-plugin, these cause file watching to break when running `skaffold debug`
        ]
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-rest-server
    context: rest-server
    jib: {}
    sync:
      auto: true
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-inventory
    context: inventory
    jib: {}
    sync:
      auto: true
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-notification
    context: notifications
    jib: {}
    sync:
      auto: true
    requires:
      - image: shared_lib
  - image: opennms/horizon-stream-keycloak-dev
    context: keycloak-ui
    sync:
      manual: # Inferred file sync is limited for multi-stage builds, use manual sync.
        - src: 'themes/**'
          dest: .
    docker:
      dockerfile: Dockerfile
      target: development
  - image: opennms/horizon-stream-grafana-dev
    context: grafana
    docker:
      dockerfile: Dockerfile

portForward:
  - resourceType: deployment
    resourceName: opennms-rest-server
    port: 9090 # HTTP
  - resourceType: deployment
    resourceName: opennms-rest-server
    port: 5005 # Debug
    localPort: 13050
  - resourceType: deployment
    resourceName: opennms-inventory
    port: 8080 # HTTP
    localPort: 28080
  - resourceType: deployment
    resourceName: opennms-inventory
    port: 5005 # Debug
    localPort: 28050
  - resourceType: deployment
    resourceName: opennms-notifications
    port: 8080 # HTTP
    localPort: 15080
  - resourceType: deployment
    resourceName: opennms-notifications
    port: 5005 # Debug
    localPort: 15050
  - resourceType: deployment
    resourceName: opennms-core
    port: 8181 # HTTP
    localPort: 11080
  - resourceType: deployment
    resourceName: opennms-core
    port: 8101 # SSH
    localPort: 11022
  - resourceType: deployment
    resourceName: opennms-core
    port: 5005 # Debug
    localPort: 11050
  - resourceType: deployment
    resourceName: opennms-minion
    port: 8181 # HTTP
    localPort: 12080
  - resourceType: deployment
    resourceName: opennms-minion
    port: 8102 # SSH
    localPort: 12022
  - resourceType: deployment
    resourceName: opennms-minion
    port: 5005 # Debug
    localPort: 12050
  - resourceType: deployment
    resourceName: onms-keycloak
    port: 8080 # HTTP
    localPort: 26080
  - resourceType: deployment
    resourceName: mail-server
    port: 8025 # HTTP
    localPort: 22080
  - resourceType: deployment
    resourceName: mail-server
    port: 1025 # SMTP
    localPort: 22025
  - resourceType: deployment
    resourceName: postgres
    port: 5432 # Postgres
    localPort: 25054
  - resourceType: deployment
    resourceName: prometheus
    port: 9090 # prometheus tcp
    localPort: 19080
  - resourceType: deployment
    resourceName: prometheus-pushgateway
    port: 9091 #prometheus-pushgateway tcp
    localPort: 21080
  - resourceType: deployment
    resourceName: grafana
    port: 3000 #grafana HTTP
    localPort: 18080
  - resourceType: deployment
    resourceName: onms-kafka
    port: 59092 # kafka tcp local client port
    localPort: 59092 # default port for kafka broker
  - resourceType: deployment
    resourceName: ingress-nginx-controller
    port: 80 # HTTP
    localPort: 8123
deploy:
  helm:
    releases:
      - name: opennms
        chartPath: charts/opennms
        valuesFiles:
          - skaffold-helm-values.yaml
        artifactOverrides:
          OpenNMS.Core.Image: opennms/horizon-stream-core
          OpenNMS.API.Image: opennms/horizon-stream-rest-server
          OpenNMS.UI.Image: opennms/horizon-stream-ui
          OpenNMS.Notification.Image: opennms/horizon-stream-notification
          OpenNMS.Inventory.Image: opennms/horizon-stream-inventory
          OpenNMS.Minion.Image: opennms/horizon-stream-minion
          OpenNMS.MinionGateway.Image: opennms/horizon-stream-minion-gateway
          Keycloak.Image: opennms/horizon-stream-keycloak-dev
          Grafana.Image: opennms/horizon-stream-grafana-dev
profiles:
  - name: prod
  - name: use-operator
    deploy:
      kubectl:
        manifests:
          - skaffold-custom-resource.yaml
      helm:
        releases: []
    resourceSelector:
      allow:
        - groupKind: "OpenNMS.k8s.opennms.com"
          image: [ ".*" ]
          labels: [ ".*" ]
