apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.Inventory.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.Inventory.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.OpenNMS.Inventory.Port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.OpenNMS.Inventory.ServiceName }}
