apiVersion: v1
kind: Secret # Currently stores passwords!
metadata:
  name: {{ .Values.Grafana.ServiceName }}
  labels:
    app: {{ .Values.Grafana.ServiceName }}
  namespace: {{ .Values.Namespace }}
stringData:
  grafana.ini: |
    [database]
    type = postgres
    host = {{ .Values.Postgres.ServiceName }}:5432
    name = grafana
    user = grafana
    password = {{ .Values.Postgres.GrafanaPassword }}

    [analytics]
    check_for_updates = true

    [grafana_net]
    url = https://grafana.net

    [log]
    mode = console

    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
    [log]
    level = info

    #################################### SECURITY ####################################
    [security]
    disable_initial_admin_creation = false
    
    admin_user = place_holder_for_k8s_secret
    
    admin_password = place_holder_for_k8s_secret

    #################################### Server ##############################
    [server]

    protocol = http
    
    http_addr =

    #Leave blank
    http_port = 
    
    domain = {{ .Values.Host }}
    
    enforce_domain = false
    
    root_url = %(protocol)s://%(domain)s{{ .Values.Grafana.Path}}
    
    serve_from_sub_path = true

    router_logging = false
    
    static_root_path = public
    
    enable_gzip = false
    
    cert_file =
    cert_key =
    
    socket = /tmp/grafana.sock

    cdn_url =
    
    read_timeout = 0

    ########KEYCLOAK############
    
    [auth.generic_oauth]
    enabled = true
    scopes = openid email profile
    name = Oauth
    tls_skip_verify_insecure = true
    allow_sign_up = true
    client_id = grafana
    client_secret = grafana-client-secret
    auth_url =  https://{{ .Values.Host }}{{ .Values.Keycloak.Path }}/realms/{{ .Values.Keycloak.RealmName }}/protocol/openid-connect/auth

    # The following point to the service in the cluster.
    token_url = https://{{ .Values.Host }}{{ .Values.Keycloak.Path }}/realms/{{ .Values.Keycloak.RealmName }}/protocol/openid-connect/token
    api_url =   https://{{ .Values.Host }}{{ .Values.Keycloak.Path }}/realms/{{ .Values.Keycloak.RealmName }}/protocol/openid-connect/userinfo

  default.yml: |
    apiVersion: 1
    
    datasources:
      - name: hs-metrics
        type: prometheus
        access: proxy
        orgId: 1
        url: http://{{ .Values.Prometheus.Server.ServiceName }}:{{ .Values.Prometheus.Server.Port }}
        isDefault: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        ## <string> json object of data that will be encrypted.
        secureJsonData:
          httpHeaderValue1: "{{ .Values.Namespace }}"
        version: 1
        # <bool> allow users to edit datasources from the UI.
        editable: false
  dashboard.yml: |
    apiVersion: 1
    
    providers:
      - name: "Horizon stream"
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: "/usr/share/grafana/public/dashboards"
          foldersFromFilesStructure: true
  opennms-entities.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "collapsed": false,
          "datasource": null,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 17
          },
          "id": 2,
          "panels": [],
          "title": "Minions",
          "type": "row"
        },
        {
          "datasource": "hs-metrics",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 18
          },
          "id": 4,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single"
            }
          },
          "targets": [
            {
              "exemplar": true,
              "expr": "minion_response_time_msec",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "title": "Mininon Response Time",
          "type": "timeseries"
        },
        {
          "datasource": "hs-metrics",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 26
          },
          "id": 6,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single"
            }
          },
          "targets": [
            {
              "exemplar": true,
              "expr": "minion_uptime_sec",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "title": "Minion UP Time",
          "type": "timeseries"
        }
      ],
      "refresh": "1m",
      "schemaVersion": 32,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "brower",
      "title": "Horizon Stream"
    }
type: Opaque
