apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.Notification.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.Notification.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.Notification.ServiceName }}
  replicas: {{ .Values.OpenNMS.Notification.Replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.OpenNMS.Notification.ServiceName }}
    spec:
      containers:
        - name: {{ .Values.OpenNMS.Notification.ServiceName }}
          image: {{ .Values.OpenNMS.Notification.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.Notification.ImagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y" # Permanent debug port in `skaffold dev`
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.Kafka.ServiceName }}:{{ .Values.Kafka.Port }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: notificationUser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: notificationPwd
            - name: HORIZON_KEYCLOAK_BASE_URL
              value: "http://{{ .Values.Keycloak.ServiceName }}:{{ .Values.Keycloak.Port }}{{ .Values.Keycloak.Path }}/"
            - name: HORIZON_KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
                  key: username
            - name: HORIZON_KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
                  key: password
          ports:
            - name: http
              containerPort: {{ .Values.OpenNMS.Notification.Port }}
