apiVersion: v1
entries:
  opennms:
  - apiVersion: v2
    created: "2022-09-26T15:01:26.109658-04:00"
    digest: fefba906fdd235f9ad57dee57973fd12f6c2d9906d2a971745279dbeb0409499
    name: opennms
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    created: "2022-09-26T15:01:26.108343-04:00"
    digest: fe3318c6c684061da0a8e10b53eea48aa557e489a99089685186c08b697dd909
    name: opennms
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    created: "2022-09-22T09:45:02.913272-04:00"
    digest: fc12f321e40ce723a42cccb25da37b15d29a2ab56bf0dca480d1e7a32d5726af
    name: opennms
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    created: "2022-09-26T15:01:26.107047-04:00"
    digest: 6c7ff0329b30e75c37c27997c31364feade43be327042bd88a74f65f85484100
    name: opennms
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    created: "2022-09-26T15:01:26.105904-04:00"
    digest: 6306ff0d5e059ea56fcdf26be5470a90408dcf71c975d137004261b6afacc837
    name: opennms
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-0.1.1.tgz
    version: 0.1.1
  opennms-operator:
  - apiVersion: v2
    created: "2022-09-26T15:01:26.111339-04:00"
    description: A Kubernetes operator for deploying and maintaining OpenNMS in the
      cloud.
    digest: 65861f5ae4023fdd20ac7dac850fb5c170032bad1688be4f740d1f9df7dc4822
    home: https://github.com/OpenNMS/horizon-stream
    icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Horizontal-Logo_Light-BG-retina-website.png
    maintainers:
    - email: jkapp@opennms.com
      name: Jeffrey-David Kapp
    name: opennms-operator
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    created: "2022-09-26T15:01:26.11109-04:00"
    description: A Kubernetes operator for deploying and maintaining OpenNMS in the
      cloud.
    digest: f140d9701ff28625db9116a31e9d1bb86ff278a6aa8abeb55bee7d4961de9dc1
    home: https://github.com/OpenNMS/horizon-stream
    icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Horizontal-Logo_Light-BG-retina-website.png
    maintainers:
    - email: jkapp@opennms.com
      name: Jeffrey-David Kapp
    name: opennms-operator
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    created: "2022-09-22T09:45:02.916389-04:00"
    description: A Kubernetes operator for deploying and maintaining OpenNMS in the
      cloud.
    digest: cd34fc400db2560c8620b057b930d1b67e539fd4fc5be0af0451524d40f668af
    home: https://github.com/OpenNMS/horizon-stream
    icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Horizontal-Logo_Light-BG-retina-website.png
    maintainers:
    - email: jkapp@opennms.com
      name: Jeffrey-David Kapp
    name: opennms-operator
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    created: "2022-09-26T15:01:26.110726-04:00"
    description: A Kubernetes operator for deploying and maintaining OpenNMS in the
      cloud.
    digest: c8ff1ab6f66feb32907d4b6486684fe8bdb6d0cd82b4a13bebe81f8f3f72d1c4
    home: https://github.com/OpenNMS/horizon-stream
    icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Horizontal-Logo_Light-BG-retina-website.png
    maintainers:
    - email: jkapp@opennms.com
      name: Jeffrey-David Kapp
    name: opennms-operator
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    created: "2022-09-26T15:01:26.110239-04:00"
    description: A Kubernetes operator for deploying and maintaining OpenNMS in the
      cloud.
    digest: 2004c4ba1b805007b2527fe3260d65fc2f2e917399cd41f44b2a5adcd88684ac
    home: https://github.com/OpenNMS/horizon-stream
    icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Horizontal-Logo_Light-BG-retina-website.png
    maintainers:
    - email: jkapp@opennms.com
      name: Jeffrey-David Kapp
    name: opennms-operator
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-0.1.1.tgz
    version: 0.1.1
  opennms-operator-dependencies:
  - apiVersion: v2
    created: "2022-09-26T15:01:26.112674-04:00"
    dependencies:
    - name: kubernetes-replicator
      repository: https://helm.mittwald.de
      version: 2.7.3
    digest: 6990f556ee3597097a9e07d2d66bd905deef1f6a0f7965244c6e89c3fba848f5
    name: opennms-operator-dependencies
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-dependencies-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    created: "2022-09-22T09:45:02.917951-04:00"
    dependencies:
    - name: kubernetes-replicator
      repository: https://helm.mittwald.de
      version: 2.7.3
    digest: 74673f78c4e5a2ffd86889efc0b46629658d100ef9827d5ed10161393cbd26e4
    name: opennms-operator-dependencies
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-dependencies-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    created: "2022-09-26T15:01:26.112111-04:00"
    dependencies:
    - name: kubernetes-replicator
      repository: https://helm.mittwald.de
      version: 2.7.3
    digest: f1fa9b1d221b41fca3d5560a114ab330642282ca12c571af458b93b4f2bfab78
    name: opennms-operator-dependencies
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-dependencies-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    created: "2022-09-26T15:01:26.111625-04:00"
    digest: 5fd26a59231ab173a8b7b0b51e60575bf955fdc11615a3bd65b30da5690e074d
    name: opennms-operator-dependencies
    urls:
    - https://opennms.github.io/horizon-stream/charts/packaged/opennms-operator-dependencies-0.1.0.tgz
    version: 0.1.0
generated: "2022-09-26T15:01:26.104608-04:00"
