server:
  port: 9090

# graphql
graphql:
  spqr:
    gui:
      enabled: true
    base-packages:
      - org.opennms.horizon.shared.dto

# keycloak admin client properties
horizon-stream:
  core:
    url: http://localhost:8181
  notifications:
    url: http://localhost:15080

logging:
  file.path: /var/log/restServer

tsdb.url: http://localhost:59090/api/v1/query
