apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: {{ .Values.Postgres.ServiceName }}
  namespace: {{ .Values.Namespace }}
data:
  adminUser: "{{ "postgres" | b64enc }}"
  adminPwd: "{{ .Values.Postgres.AdminPassword | b64enc }}"
  opennmsUser: "{{ "opennms" | b64enc }}"
  opennmsPwd: "{{ .Values.Postgres.OpenNMSPassword | b64enc }}"
  keycloakUser: "{{ "keycloak" | b64enc }}"
  keycloakPwd: "{{ .Values.Postgres.KeycloakPassword | b64enc }}"
  notificationUser: "{{ "notification" | b64enc }}"
  notificationPwd: "{{ .Values.Postgres.NotificationPassword | b64enc }}"
  grafanaUser: "{{ "grafana" | b64enc }}"
  grafanaPwd: "{{ .Values.Postgres.GrafanaPassword | b64enc }}"
type: Opaque
