apiVersion: v1
kind: Secret # Currently stores passwords!
metadata:
  labels:
    app: {{ .Values.Postgres.ServiceName }}
  name: postgres-initial-sql
  namespace: {{ .Values.Namespace }}
stringData:
  postgres.initial.script.sql: |
    CREATE USER opennms with password '{{ .Values.Postgres.OpenNMSPassword }}';
    CREATE DATABASE horizon_stream;
    GRANT ALL ON DATABASE horizon_stream TO opennms;
  postgres.keycloak.initial.script.sql: |
    CREATE USER keycloak with password '{{ .Values.Postgres.KeycloakPassword }}';
    CREATE DATABASE keycloak;
    GRANT ALL ON DATABASE keycloak TO keycloak;
  postgres.notification.initial.script.sql: |
    CREATE USER notification with password '{{ .Values.Postgres.NotificationPassword }}';
    CREATE DATABASE notification;
    GRANT ALL ON DATABASE notification TO notification;
  postgres.grafana.initial.script.sql: |
    CREATE USER grafana with password '{{ .Values.Postgres.GrafanaPassword }}';
    CREATE DATABASE grafana;
    GRANT ALL ON DATABASE grafana TO grafana;
type: Opaque
