# nonk8s
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: minion-gateway
requires:
  - configs: [ "parent-pom" ]
    path: ../parent-pom/skaffold.yaml
  - configs: [ "shared-lib" ]
    path: ../shared-lib/skaffold.yaml
build:
  artifacts:
    - image: opennms/horizon-stream-minion-gateway
      jib:
        project: main
        args:
          - package
      sync:
        auto: true
      requires:
        - image: parent-pom
          alias: unused_parent
        - image: shared-lib
          alias: unused_shared
