# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-{{ .Values.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/part-of: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/version: 1.3.0
  name: ingress-nginx-controller
  namespace: {{ .Values.Namespace }}
spec:
  ports:
    - appProtocol: http
      name: http
      port: {{ .Values.Ingress.HttpPort }}
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      port: {{ .Values.Ingress.HttpsPort }}
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: controller-{{ .Values.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Values.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Values.Namespace }}
