apiVersion: k8s.opennms.com/v1alpha1
kind: OpenNMS
metadata:
  name: local-instance
spec:
  allowedUsers: []
  host: onmshs
  httpPort: 80
  httpsPort: 443
  namespace: local-instance
  deployOnly: true
  core:
    image: opennms/horizon-stream-core
    cpu: "0"
    mem: "0"
  api:
    image: opennms/horizon-stream-rest-server
    cpu: "0"
    mem: 500Mi
  ui:
    image: opennms/horizon-stream-ui
    cpu: "0"
    mem: 100Mi
  minion:
    image: opennms/minion:29.0.10
    cpu: "0"
    mem: 500Mi
  notification:
    image: opennms/horizon-stream-notification
    cpu: "0"
    mem: 100Mi
  keycloak:
    image: opennms/horizon-stream-keycloak:latest
  grafana:
    image: opennms/horizon-stream-grafana
  postgres:
    image: postgres:13.3-alpine
  credentials:
    adminPassword: admin
    userPassword: passw0rd
