name: release

on:
  push:
    branches:
      - 'release'

# For now, we have put all steps into a single job, this will allow for just
# one vm to run. We use actions to factor out the functionality. If there is a
# requirement to create additional jobs, maybe to run concurrent jobs, then we
# can split them up later.

jobs:
  release:
    runs-on: ubuntu-latest
    environment: docker-publish-account
    # Enviroment that contains the required secrets.
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        # Is required to call actions.

      - name: init
        run: |

          TAG=$(echo ${{ github.event.head_commit.message }} | awk '{ print $2 }')

          echo "Head commit message: ${{ github.event.head_commit.message }}"
          echo "Extracted tag: $TAG."

          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

          # Validate tag format
          # Format of commit message: RELEASE <tag> - <message>
          # Format of tag (change numbers or dev, but leave everything else): 
          #   v0.0.5-dev
          #   v0.0.5
          if [[ $TAG =~ ^v[0-9]+.[0-9]+.([0-9]+-[a-z]+|[0-9]+)$ ]]
          then
            echo "Valid format, proceed with test."
          else
            echo "Tag format is invalid."
            exit 1
          fi

      - name: parent-pom
        id: action-parent-pom
        uses: ./.github/actions/parent-pom
        with:
          dir-location: 'parent-pom'

      - name: feature-grafana
        id: action-grafana
        uses: ./.github/actions/grafana
        with:
          dir-location: 'grafana'

      - name: feature-keycloak-ui
        id: action-feature-keycloak-ui
        uses: ./.github/actions/keycloak-ui
        with:
          dir-location: 'keycloak-ui'

      - name: feature-ui
        id: action-feature-ui
        uses: ./.github/actions/ui
        with:
          dir-location: 'ui'

      # This needs to happen before core, rest-server, inventory, and notifications.
      - name: shared-lib
        id: action-shared-lib
        uses: ./.github/actions/shared-lib
        with:
          dir-location: 'shared-lib'

      - name: feature-core
        id: action-feature-core
        uses: ./.github/actions/core
        with:
          dir-location: 'platform'

      - name: feature-rest-server
        id: action-rest-server
        uses: ./.github/actions/rest-server
        with:
          dir-location: 'rest-server'

      - name: feature-inventory
        id: action-inventory
        uses: ./.github/actions/inventory
        with:
          dir-location: 'inventory'
      
      - name: feature-notifications
        id: action-notifications
        uses: ./.github/actions/notifications
        with:
          dir-location: 'notifications'
      
      - name: feature-operator
        id: action-feature-operator
        uses: ./.github/actions/operator
        with:
          dir-location: 'operator'

      #- name: external-it
      #  id: action-external-it
      #  uses: ./.github/actions/external-it
      #  with:
      #    dir-location: 'external-it'
      
      - name: dockerhub-login
        run: |

          # This and the following steps are put here rather than put into an
          # action because it is only ever called from this workflow.

          # Login to dockerhub. The session doesn't seem to carry across steps,
          # re-test to confirm.
          #docker login -u ${{ secrets.DOCKERHUB_LOGIN }} -p ${{ secrets.DOCKERHUB_PASS }}
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

      - name: publish-image-core
        run: |

          # Login to dockerhub.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Publish core image
          cd platform/

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/horizon-stream-core:local opennms/horizon-stream-core:${{ env.RELEASE_TAG }}
          docker tag opennms/horizon-stream-core:local opennms/horizon-stream-core:latest

          docker push opennms/horizon-stream-core:${{ env.RELEASE_TAG }}
          docker push opennms/horizon-stream-core:latest
      
      - name: publish-image-ui
        run: |

          # Login to dockerhub.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/horizon-stream-ui:local opennms/horizon-stream-ui:${{ env.RELEASE_TAG }}
          docker tag opennms/horizon-stream-ui:local opennms/horizon-stream-ui:latest

          docker push opennms/horizon-stream-ui:${{ env.RELEASE_TAG }}
          docker push opennms/horizon-stream-ui:latest

      - name: publish-image-keycloak-ui
        run: |

          # Login to dockerhub.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/horizon-stream-keycloak:local opennms/horizon-stream-keycloak:${{ env.RELEASE_TAG }}
          docker tag opennms/horizon-stream-keycloak:local opennms/horizon-stream-keycloak:latest

          docker push opennms/horizon-stream-keycloak:${{ env.RELEASE_TAG }}
          docker push opennms/horizon-stream-keycloak:latest

      - name: publish-image-grafana
        run: |

          # Login to dockerhub.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/horizon-stream-grafana:local opennms/horizon-stream-grafana:${{ env.RELEASE_TAG }}
          docker tag opennms/horizon-stream-grafana:local opennms/horizon-stream-grafana:latest

          docker push opennms/horizon-stream-grafana:${{ env.RELEASE_TAG }}
          docker push opennms/horizon-stream-grafana:latest

      - name: publish-image-rest-server
        run: |

          # Login to dockerhub. Probably could remove this, session created in previous step.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Test build images
          docker images

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/horizon-stream-rest-server:local opennms/horizon-stream-rest-server:${{ env.RELEASE_TAG }}
          docker tag opennms/horizon-stream-rest-server:local opennms/horizon-stream-rest-server:latest

          docker push opennms/horizon-stream-rest-server:${{ env.RELEASE_TAG }}
          docker push opennms/horizon-stream-rest-server:latest

      - name: publish-image-inventory
        run: |

          # Login to dockerhub. Probably could remove this, session created in previous step.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Test build images
          docker images

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/horizon-stream-inventory:local opennms/horizon-stream-inventory:${{ env.RELEASE_TAG }}
          docker tag opennms/horizon-stream-inventory:local opennms/horizon-stream-inventory:latest

          docker push opennms/horizon-stream-inventory:${{ env.RELEASE_TAG }}
          docker push opennms/horizon-stream-inventory:latest
      
      - name: publish-image-notifications
        run: |

          # Login to dockerhub. Probably could remove this, session created in previous step.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Test build images
          docker images

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/horizon-stream-notification:local opennms/horizon-stream-notification:${{ env.RELEASE_TAG }}
          docker tag opennms/horizon-stream-notification:local opennms/horizon-stream-notification:latest

          docker push opennms/horizon-stream-notification:${{ env.RELEASE_TAG }}
          docker push opennms/horizon-stream-notification:latest
      
      - name: publish-image-operator
        run: |

          # Login to dockerhub.
          echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          # Tag and save the image as a file to be published. Both release version and latest.
          docker tag opennms/operator:local-build opennms/operator:${{ env.RELEASE_TAG }}
          docker tag opennms/operator:local-build opennms/operator:latest

          docker push opennms/operator:${{ env.RELEASE_TAG }}
          docker push opennms/operator:latest

      - name: tag-release-branch
        run: |

          # The following checkouts the release branch and merges develop into
          # it and then tags release.
          git fetch
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}


